name: clima_a_weather_app
description: Clima is a weather app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  http: ^1.4.0
  geolocator: ^14.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  go_router: ^15.2.4
  app_settings: ^6.1.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/certificates/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf
          weight: 900


